### ISSUE TITLE
AttributeError: 'Databases' object has no attribute 'REF_DIR'

### ISSUE THREAD

**Issue by Thexiyang** [geronimp/enrichM#101]
Thank for the nice tool! I downloaded the database manually and specified its location. However, I when used enirchm annotate, there is one error message come out. It reads as follows. Could you give me some hints on how I can solve it? Thanks! 

```
-bash-4.2$ enrichm annotate --genome_files reference.faa
[2020-03-30 06:44:36 AM] INFO: Command:enrichm annotate --genome_files reference.faa
[2020-03-30 06:44:36 AM] INFO: Running the annotate pipeline
Traceback (most recent call last):
  File "/enrichm/bin/enrichm", line 342, in <module>
    run.run_enrichm(args, sys.argv)
  File "/enrichm/lib/python3.7/site-packages/enrichm/run.py", line 305, in run_enrichm
    args.threads, args.parallel, args.suffix, args.light)
  File "/enrichm/lib/python3.7/site-packages/enrichm/annotate.py", line 122, in __init__
    self.databases = Databases()
  File "/enrichm/lib/python3.7/site-packages/enrichm/databases.py", line 98, in __init__
    self.KO_DB = os.path.join(self.REF_DIR, self.KO_DB_NAME + self.DMND_SUFFIX)
AttributeError: 'Databases' object has no attribute 'REF_DIR'
```

**Comment by geronimp** [comment]
Hi there,

Thank you for using enrichm!

Apologies for the unclear error message, would you be able to try and run enrichm annotate with an annotate option (either --ko --cazy --tigrfam or --pfam) and let me know if this error still occurs?

Thanks,

Joel

**Comment by Thexiyang** [comment]
Thanks for the reply. I tried. Same issue.

**Comment by geronimp** [comment]
Would you please be able to confirm for me that you are using version 0.5.0?

**Comment by Thexiyang** [comment]
Yes. I installed using conda and then upgraded to 0.5.0 using pip. It looks it did not look for the database.

**Comment by jianshu93** [comment]
I have the same issue with 0.5.0 but. Is it solved?Thanks

**Comment by liupfskygre** [comment]
Hi, 
the same issue here, is this being solved? thanks.

 Version: 0.5.0
```
Traceback (most recent call last):
  File "/home/dell/.conda/envs/enrichm/bin/enrichm", line 342, in <module>
    run.run_enrichm(args, sys.argv)
  File "/home/dell/.conda/envs/enrichm/lib/python3.7/site-packages/enrichm/run.py", line 305, in run_enrichm
    args.threads, args.parallel, args.suffix, args.light)
  File "/home/dell/.conda/envs/enrichm/lib/python3.7/site-packages/enrichm/annotate.py", line 122, in __init__
    self.databases = Databases()
  File "/home/dell/.conda/envs/enrichm/lib/python3.7/site-packages/enrichm/databases.py", line 98, in __init__
    self.KO_DB = os.path.join(self.REF_DIR, self.KO_DB_NAME + self.DMND_SUFFIX)
AttributeError: 'Databases' object has no attribute 'REF_DIR'

```

**Comment by jianshu93** [comment]
i do not think it's solved. Still cannot use it.

**Comment by mengyuan09876** [comment]
AttributeError: 'Databases' object has no attribute 'REF_DIR' same problem
