### ISSUE TITLE
Error opening file /home/databases/enrichm_database_v10/databases/uniref100.dmnd

### ISSUE THREAD

**Issue by zyyalice** [geronimp/enrichM#108]
Hi

I get this error when i use the following commond:

enrichm annotate --genome_directory all_cat/ --ko --threads 40 --output 1
[2020-06-28 09:21:07 AM] INFO: Running command: /home/emma/anaconda2/envs/enrichm_0.5.0/bin/enrichm annotate --genome_directory all_cat/ --ko --threads 40 --output 1
[2020-06-28 09:21:07 AM] INFO: Loading databases
[2020-06-28 09:21:07 AM] INFO: Loading reference db paths
[2020-06-28 09:21:08 AM] INFO: Running pipeline: annotate
[2020-06-28 09:21:08 AM] INFO: Setting up for genome annotation
[2020-06-28 09:21:08 AM] INFO: Calling proteins for annotation
[2020-06-28 09:21:08 AM] INFO:     - Calling proteins for 4 genomes
[2020-06-28 09:22:34 AM] INFO: Starting annotation:
[2020-06-28 09:22:34 AM] INFO:     - Annotating genomes with ko ids
[2020-06-28 09:22:34 AM] INFO:     - BLASTing genomes
No such file or directory
Error: Error opening file /home/emma/databases/enrichm_database_v10/databases/uniref100.dmnd
Traceback (most recent call last):
  File "/home/emma/anaconda2/envs/enrichm_0.5.0/bin/enrichm", line 357, in <module>
    r.main(args, sys.argv)
  File "/home/emma/anaconda2/envs/enrichm_0.5.0/lib/python3.7/site-packages/enrichm/run.py", line 323, in main
    args.protein_files)
  File "/home/emma/anaconda2/envs/enrichm_0.5.0/lib/python3.7/site-packages/enrichm/annotate.py", line 661, in do
    self.annotate_ko(genomes_list)
  File "/home/emma/anaconda2/envs/enrichm_0.5.0/lib/python3.7/site-packages/enrichm/annotate.py", line 230, in annotate_ko
    for genome_name, batch in self.get_batches(output_annotation_path):
  File "/home/emma/anaconda2/envs/enrichm_0.5.0/lib/python3.7/site-packages/enrichm/annotate.py", line 242, in get_batches
    input_file_io = open(input_file)
FileNotFoundError: [Errno 2] No such file or directory: '1/annotations_ko/DIAMOND_search.tsv'

Could you help me?
Thank you!
Looking forward to your reply.

**Comment by SvenTobias-Hunefeldt** [comment]
Hi.

How did you download enrichM? Because if you do it over conda then you end up downloading version 0.4.3, which did not have the option of hmm/diamond within the python script, while the uniref100 database file "home/emma/databases/enrichm_database_v10/databases/uniref100.dmnd" had already been split into hmmer and diamond compatible versions.

You should be able to check what version you have by calling `conda list` inside your enrvironment.

The way I fixed it is by downloading the 0.5.0 from "https://anaconda.org/bioconda/enrichm/files" and used that to install enrichM into a conda environment.
