### ISSUE TITLE
0.5.1 run error

### ISSUE THREAD

**Issue by jianshu93** [geronimp/enrichM#114]
enrichm annotate --output ./dereplicated_genomes_enrichm_annotate --genome_directory ./dereplicated_genomes --ko --pfam --tigrfam --hypothetical --cazy --threads 2 --parallel 10

error:

Traceback (most recent call last):
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/enrichm/bin/enrichm", line 4, in <module>
    __import__('pkg_resources').run_script('enrichm==0.5.1', 'enrichm')
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/enrichm/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/enrichm/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/enrichm/lib/python3.7/site-packages/enrichm-0.5.1-py3.7.egg/EGG-INFO/scripts/enrichm", line 359, in <module>
    r.main(args, sys.argv)
AttributeError: 'Run' object has no attribute 'main'
Command exited with non-zero status 1

**Comment by haiyuan-cai** [comment]
I have the same issue

**Comment by jianshu93** [comment]
add def main() to replace the if main line and also add if line and a new main() at the end of enrichm script
