### ISSUE TITLE
ERROR while classifying using custom module

### ISSUE THREAD

**Issue by ShailNair** [geronimp/enrichM#116]
Hi,
I created a tsv file with nitrogen fixation KO's, when I run the classify command I get the following error-

/home/mcs/miniconda3/envs/enrichm-0.5.0/bin/enrichm classify **--output** /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/binning/metwrap_mod/enrichM/classify_n2fix **--genome_and_annotation_matrix** /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/binning/metwrap_mod/enrichM/annotate/ko_frequency_table.tsv **--custom_modules** /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/binning/metwrap_mod/enrichM/N2.tsv
[2020-12-17 09:39:36 AM] INFO: Running the classify pipeline
[2020-12-17 09:39:36 AM] INFO: Reading in custom modules: /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/binning/metwrap_mod/enrichM/N2.tsv
[2020-12-17 09:39:36 AM] INFO: Read in annotations for 125 genomes
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/enrichm-0.5.0/bin/enrichm", line 342, in <module>
    run.run_enrichm(args, sys.argv)
  File "/home/mcs/miniconda3/envs/enrichm-0.5.0/lib/python3.6/site-packages/enrichm/run.py", line 317, in run_enrichm
    args.genome_and_annotation_matrix, args.output)
  File "/home/mcs/miniconda3/envs/enrichm-0.5.0/lib/python3.6/site-packages/enrichm/classifier.py", line 109, in classify_pipeline
    path = ModuleDescription(pathway_string)
  File "/home/mcs/miniconda3/envs/enrichm-0.5.0/lib/python3.6/site-packages/enrichm/module_description_parser.py", line 37, in __init__
    = ModuleDescriptionParser().parse_module_string(module_description_string)
  File "/home/mcs/miniconda3/envs/enrichm-0.5.0/lib/python3.6/site-packages/enrichm/module_description_parser.py", line 263, in parse_module_string
    "Parse exception on %s" % string)
**Exception: Parse exception on "(K02586,K02588,K02591)"**

Attached are the ko_frequency.tsv and custom module file
[files.zip](https://github.com/geronimp/enrichM/files/5706472/files.zip)

**Comment by geronimp** [comment]
Hi,

Thank you for your interest in enrichM, sorry for the late reply. The custom module file is mis-formatted. The quotation marks are not necessary, so if you remove them it should run fine.

Thanks,

Joel

**Comment by ShailNair** [comment]
Thanks. somehow creating the custom module in ms excel included these quotation marks.
