### ISSUE TITLE
fuzzywuzzi missing from conda env

### ISSUE THREAD

**Issue by wwood** [geronimp/enrichM#123]
```
(/home/ben/e/enrichm-0.6.3) b2:20210209:~/git/singlem-local$ enrichm -h
Traceback (most recent call last):
  File "/home/ben/e/enrichm-0.6.3/bin/enrichm", line 22, in <module>
    from enrichm.run import Run
  File "/home/ben/e/enrichm-0.6.3/lib/python3.6/site-packages/enrichm/run.py", line 11, in <module>
    from enrichm.enrichment import Enrichment
  File "/home/ben/e/enrichm-0.6.3/lib/python3.6/site-packages/enrichm/enrichment.py", line 16, in <module>
    from enrichm.synteny_searcher import SyntenySearcher
  File "/home/ben/e/enrichm-0.6.3/lib/python3.6/site-packages/enrichm/synteny_searcher.py", line 8, in <module>
    from fuzzywuzzy import fuzz, process
ModuleNotFoundError: No module named 'fuzzywuzzy'
```

Easy enough to fix with `conda install fuzzywuzzi` but I'm not sure if there is specific version requirements?

**Comment by mhyleung** [comment]
If it is not part of the initial conda package maybe can install separately within the enrichm environment?

https://anaconda.org/conda-forge/fuzzywuzzy

Marc
