### ISSUE TITLE
enrichM database

### ISSUE THREAD

**Issue by fanlu-f** [geronimp/enrichM#125]
I want to download the database. I used the command that "enrichm data" .but the database not download automatically.

(enrichm) user@user-X11DPi-N-T:~/Desktop$ enrichm data
usage: enrichm data [-h] [--log LOG] [--verbosity VERBOSITY] [--output OUTPUT]
                    [--force] [--uninstall] [--create CREATE] [--dry]

optional arguments:
  -h, --help            show this help message and exit

Logging options:
  --log LOG             Output logging information to this file.
  --verbosity VERBOSITY
                        Level of verbosity (1 - 5 - default = 4) 5 = Very verbose, 1 = Silent

Output options:
  --output OUTPUT       Output directory
  --force               Overwrite previous run

Uninstall:
  --uninstall           Remove enrichm database
  --create CREATE       create enrichm database
  --dry                 Download an empty database (debug)
None

**Comment by jsgounot** [comment]
Same problem. I think the current conda version did not include the last commit(s) (I only looked at the data.py file).

Running `enrichm`, it says version 0.6.3

I tried to run this command line : `enrichm data --create new` (there are no informations about what the `--create` value should be), which gave me this error message :

```
ModuleNotFoundError: No module named 'IPython'
```

And indeed, I did not install IPython on this conda env. I looked up a bit and I guess the last current conda version does not include the last commits, since this import has been removed [here](https://github.com/geronimp/enrichM/commit/bec0caa02aed1b51e581c76c1790ddeb39d9a022). 

Is it possible to update the current conda version with the last commits ? It's a shame that this bugs make the whole software completly unusable.

**Comment by Lucas-Maciel** [comment]
Tried v 0.5.0 but the script is not finding the db


```
enrichm data
[2021-05-26 17:06:18 PM] INFO: Command: ~/miniconda3/envs/enrichm_5/bin/enrichm data
[2021-05-26 17:06:18 PM] INFO: Running the data pipeline
Traceback (most recent call last):
  File "~/miniconda3/envs/enrichm_5/lib/python3.6/site-packages/enrichm/data.py", line 114, in do
    version_remote = urllib.request.urlopen(self.ftp + self.VERSION).readline().strip().decode("utf-8")
AttributeError: module 'urllib' has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/miniconda3/envs/enrichm_5/bin/enrichm", line 342, in <module>
    run.run_enrichm(args, sys.argv)
  File "~/miniconda3/envs/enrichm_5/lib/python3.6/site-packages/enrichm/run.py", line 288, in run_enrichm
    d.do(args.uninstall, args.dry)
  File "~/miniconda3/envs/enrichm_5/lib/python3.6/site-packages/enrichm/data.py", line 117, in do
    "Unable to find most current EnrichM database VERSION in ftp. Please complain at https://github.com/geronimp/enrichM")
Exception: Unable to find most current EnrichM database VERSION in ftp. Please complain at https://github.com/geronimp/enrichM
```


Tried the v 0.6.3 and even when you install iPython something weird happens:

```
enrichm data --create new
[2021-05-26 17:02:19 PM] INFO: Command: ~/miniconda3/envs/enrichm/bin/enrichm data --create new
[2021-05-26 17:02:19 PM] INFO: Running the data pipeline
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: 
```

**Comment by jsgounot** [comment]
For your first error with v.0.5, is it possible that it's a python version error ?

`AttributeError: module 'urllib' has no attribute 'request'` 

This has changed between python 2 and 3.

**Comment by Lucas-Maciel** [comment]
@jsgounot the version 0.5.0 came with Python 3.6.13 in the conda env. 

I manually modified the script data.py as indicated by #103 but I'm worried that something else might be wrong due to a different version.  For example, my script is clustering 2K proteins with 16 threads and 48GB for over 8 hours and still running. 

```
[2021-05-27 01:02:38 AM] INFO: Command: ~/miniconda3/envs/enrichm_5/bin/enrichm annotate --protein_files Bacteroides_vulgatus/GCF_000012825.1_ASM1282v1_protein.faa --ko --ko_hmm --pfam --tigrfam --orthologs --cazy --ec --threads 16 --parallel 16 --output Bacteroides_vulgatus/GCF_000012825.1_ASM1282v1_protein.enrichm
[2021-05-27 01:02:38 AM] INFO: Running the annotate pipeline
[2021-05-27 01:02:38 AM] INFO: Running pipeline: annotate
[2021-05-27 01:02:38 AM] INFO: Setting up for genome annotation
[2021-05-27 01:02:38 AM] INFO: Using provided proteins
[2021-05-27 01:02:38 AM] INFO: Preparing genomes for annotation
[2021-05-27 01:02:38 AM] INFO: Starting annotation:
[2021-05-27 01:02:38 AM] INFO:     - Annotating genomes with hypothetical clusters
[2021-05-27 01:02:38 AM] INFO:     - Generating MMSeqs2 database
[2021-05-27 01:02:39 AM] INFO:     - Clustering genome proteins
```

**Comment by mengyuan09876** [comment]
I try to update the database, but it shows me unable to locate enrichM database. I open the envs folder in anaconda, but I didn't find a file named like "database", could you please tell me the name of this database ， I would like to see if I can export it， thanks!

**Comment by xininR** [comment]
I installed the version 0.6.6, but the database cannot install.

```
user001@gs10026:~/App/db$ enrichm data --create
Traceback (most recent call last):
  File "/home/user001/.conda/envs/enrichm_0.6.6/bin/enrichm", line 22, in <module>
    from enrichm.run import Run
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/run.py", line 10, in <module>
    from enrichm.network_analyzer import NetworkAnalyser
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/network_analyzer.py", line 7, in <module>
    from enrichm.network_builder import NetworkBuilder
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/network_builder.py", line 8, in <module>
    from enrichm.parser import Parser
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/parser.py", line 7, in <module>
    from enrichm.annotate import Annotate
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/annotate.py", line 35, in <module>
    @dataclass
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/annotate.py", line 95, in Annotate
    databases: Databases = Databases()
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/databases.py", line 63, in __init__
    bash variable called ENRICHM_DB? (Currently I'm looking here: {Data.DATABASE_DIR})")
Exception: 
No database version file found. Have you: 
- Installed the EnrichM database using the 'enrichm data' command?
- Specified the location of the EnrichM database by exporting a bash variable called ENRICHM_DB? (Currently I'm looking here: /home/user001/App/db/enrichm_db)
```

THEN, I manually installed the database from https://data.ace.uq.edu.au/public/enrichm/enrichm_database_v10.tar.gz

compressed

another error happened:
```
(enrichm_0.6.6) user001@gs10026:~/App/db/enrichm_db$ enrichm
Traceback (most recent call last):
  File "/home/user001/.conda/envs/enrichm_0.6.6/bin/enrichm", line 22, in <module>
    from enrichm.run import Run
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/run.py", line 10, in <module>
    from enrichm.network_analyzer import NetworkAnalyser
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/network_analyzer.py", line 7, in <module>
    from enrichm.network_builder import NetworkBuilder
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/network_builder.py", line 8, in <module>
    from enrichm.parser import Parser
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/parser.py", line 7, in <module>
    from enrichm.annotate import Annotate
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/annotate.py", line 35, in <module>
    @dataclass
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/annotate.py", line 95, in Annotate
    databases: Databases = Databases()
  File "/home/user001/.conda/envs/enrichm_0.6.6/lib/python3.6/site-packages/enrichm/databases.py", line 21, in __init__
    with open(os.path.join(self.CUR_DATABASE_DIR, 'VERSION')) as out_io:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user001/App/db/enrichm_db/enrichm_database_v10/26-11-2018/VERSION'
```
Solution: move all the 'enrichm_database_v10' files into ./26-11-2018/
OR
change the name of 'enrichm_database_v10' to '26-11-2018'

```
$ mkdir 26-11-2018
$ mv VERSION ./26-11-2018/
$ mv mv *.pickle ./26-11-2018/
$ mv databases/ ./26-11-2018/
$ mv gtdb/ ids/ ./26-11-2018/
$ mv ko00000.tsv ko_cutoffs.tsv README taxonomy_gtdb.tsv ./26-11-2018/
```
Then, the enrichM can work now
```
(enrichm_0.6.6) user001@gs10026:~/App/db/enrichm_db$ enrichm
                         _____            _      _     __  __ 
                        | ____|_ __  _ __(_) ___| |__ |  \/  |
                        |  _| | '_ \| '__| |/ __| '_ \| |\/| |
                        | |___| | | | |  | | (__| | | | |  | |
                        |_____|_| |_|_|  |_|\___|_| |_|_|  |_|
  ------------------------------------------------------------------------------------

  Annotation
    annotate        -> Genome annotation pipeline.

  Enrichment analysis
    classify        -> Determine what pathways a genome encodes.
    enrichment      -> Calculate enrichment of functional genes between groups.

  Network analysis
    pathway         -> Generate a metabolic network from specific KEGG module or
                       compounds.
    explore         -> Take steps into metabolism using a KEGG compound ID as a 
                       starting point. Useful to see which pathways use a compound
                       of interest.

  Machine learning
    generate        -> Generate a random forest model.
    predict         -> Run random forest model on new data.

  Authors: Joel Boyd, Ben Woodcroft, Alex Baker
  Version: 0.6.6
```

```
(enrichm_0.6.6) user001@gs10026:~/08.enrichM$ enrichm classify --genome_and_annotation_matrix enrichM.txt --output ./enrichM
[2025-12-13 00:33:11 AM] INFO: Command: /home/user001/.conda/envs/enrichm_0.6.6/bin/enrichm classify --genome_and_annotation_matrix enrichM.txt --output ./enrichM
[2025-12-13 00:33:11 AM] INFO: Running the classify pipeline
[2025-12-13 00:33:11 AM] INFO: Reading in annotations from an input matrix
[2025-12-13 00:33:11 AM] INFO: Read in annotations for 5 genomes
[2025-12-13 00:33:27 AM] INFO: Writing results to file: ./enrichM/module_completeness.tsv
[2025-12-13 00:33:30 AM] INFO: Writing results to file: ./enrichM/module_paths.tsv
[2025-12-13 00:33:32 AM] INFO: Finished running EnrichM
```
