### ISSUE TITLE
AttributeError: 'Databases' object has no attribute 'M2DEF'

### ISSUE THREAD

**Issue by wdp9966** [geronimp/enrichM#126]
Thanks for your nice tool.  When I used enrichm_0.6.3, the database was manually downloaded. But there is one error message come out. I don't know how to solve it. 

[2021-04-20 00:16:21 AM] INFO: Running command: /home/wdp/.conda/envs/enrichm_0.6.3/bin/enrichm annotate --output enrichm --protein_directory /usr/local/usrdata_16T/wdp/home/test_protein/ --ko --pfam --tigrfam --hypothetical --cazy --threads 36 --parallel 36 --force
[2021-04-20 00:16:21 AM] INFO: Loading databases
Traceback (most recent call last):
  File "/home/wdp/.conda/envs/enrichm_0.6.3/bin/enrichm", line 357, in <module>
    r.main(args, sys.argv)
  File "/home/wdp/.conda/envs/enrichm_0.6.3/lib/python3.7/site-packages/enrichm/run.py", line 319, in main
    args.light)
  File "/home/wdp/.conda/envs/enrichm_0.6.3/lib/python3.7/site-packages/enrichm/annotate.py", line 120, in __init__
    self.databases        = Databases()
  File "/home/wdp/.conda/envs/enrichm_0.6.3/lib/python3.7/site-packages/enrichm/databases.py", line 97, in __init__
    self.m2def = self.load_pickle(self.M2DEF)
AttributeError: 'Databases' object has no attribute 'M2DEF'

Thanks very much!

**Comment by wdp9966** [comment]
I have automatically downloaded the database with the "enrichm data", and resolved this issue. While no folder "26-11-2018" was found in the automatically database, and all files in the "26-11-2018" were listed in the "/databases/enrichm_database_v10/" together with the folder "databases", "gtdb" and "ids". Meanwhile, the file "uniref100.KO.dmnd" in the databases was renamed as "uniref100.dmnd", beacuse of the issue "
INFO:     - BLASTing genomes
No such file or directory
Error: Error opening file /databases/enrichm_database_v10/databases/uniref100.dmnd"
Thanks very much!
