### ISSUE TITLE
Error when downloading database 

### ISSUE THREAD

**Issue by liangjinsong** [geronimp/enrichM#88]
First I installed enrichM via conda following the steps below.
conda create -n enrichm_0.5.0 python=3
conda activate enrichm_0.5.0
conda install -c bioconda mcl R hmmer diamond prodigal parallel openmp mmseqs2 moreutils
conda install -c geronimp enrichm
R
install.packages('gridExtra')
install.packages('optparse')
q()

After the installation steps above, I downloaded the database using "enrichm data" command, then a error happened, which was showed below. Can you help to solve the problem? Thank you!

(enrichm_0.5.0) jinsong@server:/data/liangjinsong/N_update/single_group_assembly_bin/5_N_genes_usearch$ enrichm data
Traceback (most recent call last):
  File "/data/software/miniconda3/envs/enrichm_0.5.0/bin/enrichm", line 357, in <module>
    r.main(args, sys.argv)
  File "/data/software/miniconda3/envs/enrichm_0.5.0/lib/python3.7/site-packages/enrichm/run.py", line 283, in main
    self._check_general(args)
  File "/data/software/miniconda3/envs/enrichm_0.5.0/lib/python3.7/site-packages/enrichm/run.py", line 116, in _check_general
    raise Exception('The following dependencies need to be installed to run enrichm:\n%s' % (dependency_string))
Exception: The following dependencies need to be installed to run enrichm:
	seqmagick	https://fhcrc.github.io/seqmagick

**Comment by liangjinsong** [comment]
Installing 'seqmagick' using 'conda install -c bioconda seqmagick' command fixed the error.
